export enum CampoFormularioType {
    Text = 'text',
    Password = 'password',
    Email = 'email',
    Url = 'url',
    Tel = 'tel',
    Date = 'date',
    DateTime = 'datetime-local',
    Textarea = 'textarea',
    Select = 'select',
    Number = 'number',
    // textarea = 'textarea',
    // mask = 'mask',
    // autoComplete = 'autoComplete',
    // file = 'file',
    // inputNumber = 'inputNumber',
    // separator = 'separator',
}